
export const SET_FILE_SYSTEM = "SET_FILE_SYSTEM";
export const TOGGLE_FILE_CHECK = "TOGGLE_FILE_CHECK";
export const ADD_FILE_TABS = "ADD_FILE_TABS";
export const REMOVE_FILE_TABS = "REMOVE_FILE_TABS";
